# CodeRabbit Configuration
# AI-assisted code review for pull requests
# Documentation: https://docs.coderabbit.ai/guides/configure-coderabbit

language: en-US

reviews:
  # Enable high-level summary of changes
  high_level_summary: true

  # Generate poem at the end of review (fun team feature)
  poem: false

  # Review status to post
  review_status: true

  # Collapse walkthrough for cleaner PR view
  collapse_walkthrough: true

  # Auto-review on PR open/update
  auto_review:
    enabled: true
    # Ignore drafts until ready
    drafts: false
    # Base branch to compare against
    base_branches:
      - main

  # Path-based instructions for reviewers
  path_instructions:
    - path: "src/app/**/*.tsx"
      instructions: |
        Review for:
        1. Design system compliance - must use components from @/components/ui-healthcare
        2. No hardcoded colors (hex values) - use semantic components
        3. FHIR data must use Medplum hooks (useMedplum, useSearchResources)
        4. PHI logging - never log patient names, DOB, or other identifiers

    - path: "src/components/ui-healthcare/**"
      instructions: |
        This is the design system. Changes here affect the entire application.
        Review for:
        1. Backward compatibility
        2. Consistent prop naming
        3. Accessibility (aria labels, keyboard navigation)
        4. TypeScript types for all props

    - path: "src/lib/design-system/**"
      instructions: |
        Design token and helper changes. Review for:
        1. PDC thresholds must be: >=80% pass, 60-79% at-risk, <60% fail
        2. Color mappings must match UI_DESIGN_SYSTEM.md
        3. Helper functions must be deterministic (no AI/randomness)

    - path: "**/*.test.ts"
      instructions: |
        Test file review:
        1. Edge cases covered (boundary values like PDC 79%, 80%)
        2. Error scenarios tested
        3. No hardcoded test data that could be PHI

# Chat capabilities in PR comments
chat:
  auto_reply: true

# Early access features
early_access: false

# Knowledge base (learns from repo patterns)
knowledge_base:
  learnings:
    scope: auto
  issues:
    scope: auto
  pull_requests:
    scope: auto
